#define CREATE 257
#define IDENTIFIER 258
#define END 259
#define PARENTESIS_IZQUIERDO 260
#define PARENTESIS_DERECHO 261
#define DOTCOMA 262
#define COMA 263
#define PARENTESIS_CUADRADO_IZQUIERDO 264
#define PARENTESIS_CUADRADO_DERECHO 265
#define COLUMN_MODIFIER 266
#define DATATYPE 267
#ifdef YYSTYPE
#undef  YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
#endif
#ifndef YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
typedef union{
	char *mystring;
} YYSTYPE;
#endif /* !YYSTYPE_IS_DECLARED */
extern YYSTYPE yylval;
